mango/urls.py
from django.urls import path
from django.conf.urls import url
from mango import views
from .views import transactionUpdate, transactionsList, transactionDelete

app_name = 'mango'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/', views.account_view, name='account'),
    path('account/add_account/', views.add_account_view, name='add_account'),
    path('account/add_transaction/', views.add_transaction_view, name="add_transaction"),
    path('account/transactions_list', transactionsList.as_view(), name="transaction_list"),
    path('account/transactions_list/update_transaction/<int:pk>', transactionUpdate.as_view(), name="update_transaction"),
    path('account/transactions_list/delete_transaction/<int:pk>', transactionDelete.as_view(), name="delete_transaction"),

]

mango_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from mango import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name="index"),
    path('mango/', include("mango.urls")),

]

mango/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.urls import reverse
# Create your models here.

# Used to manage BaseUserManager
class userAccountManager(BaseUserManager):
    def create_user(self, email, username, password):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")
        if not password:
            raise ValueError("Users must have an password")
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user 
    
    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )

        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

# Creation of custon User class to have userUUID
class userAccount(AbstractBaseUser):
    # Required Fields
    email = models.EmailField(verbose_name='email', max_length=128 , unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    # Extra Field
    user_id = models.AutoField(primary_key=True)
    password = models.CharField(max_length=20)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = userAccountManager()

    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

# Account Table
class Account(models.Model):
    account_ID = models.AutoField(primary_key=True)
    account_PlaidID = models.CharField(max_length=128,unique=True, null=True, editable=False)
    account_name = models.CharField(max_length=128)
    account_type = models.CharField(max_length=128)

    # This connects the account to a user, A user can have many accounts
    user = models.ForeignKey(userAccount, on_delete=models.CASCADE)

    def __str__(self):
        return self.account_name + " - " + self.account_type


class Category(models.Model):
    category_ID = models.AutoField(primary_key=True, editable=False)
    category_name = models.CharField(max_length=128, null=False)
    category_color = models.CharField(max_length=11, null=False)

    def __str__(self):
        return self.category_name

class Transactions(models.Model):
    transaction_ID = models.AutoField(primary_key=True, editable=False)
    transaction_plaidID = models.CharField(max_length=128, unique=True, null=True, editable=False)
    transaction_name = models.CharField(max_length=128, null=False)
    transaction_amount = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    transaction_location = models.CharField(max_length=256, editable=True, null=True)
    transaction_date = models.DateField(auto_now=False)

    # The keys that its related to
    account= models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.transaction_name

mango/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from mango.models import userAccount, Account, Transactions

# Register user
class registrationForm(UserCreationForm):
    email = forms.EmailField(max_length=128, help_text="Required. Add a valid email addresss")

    class Meta:
        model = userAccount
        fields = ("email", "username","first_name", "last_name", "password1", "password2")

# Log user in
class loginForm(forms.ModelForm):
    password = forms.CharField(label="password", widget=forms.PasswordInput)

    class Meta:
        model = userAccount
        fields = ('email', 'password')
    
    def clean(self):
        if self.is_valid:
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")

class accountUpdateForm(forms.ModelForm):
    class Meta:
        model = userAccount
        fields = ('email', 'username')

    def clean_email(self):
        if self.is_valid:
            email = self.cleaned_data['email']
            try:
                # Check if account exists
                account = userAccount.objects.exclude(pk=self.instance.pk).get(email=email)
            except userAccount.DoesNotExist:
                return email
            raise forms.ValidationError("Email {} is already in use".format(account.email))

    def clean_username(self):
        if self.is_valid:
            username = self.cleaned_data['username']
            try:
                # Check if account exists
                account = userAccount.objects.exclude(pk=self.instance.pk).get(username=username)
            except userAccount.DoesNotExist:
                return username
            raise forms.ValidationError("Email {} is already in use".format(account.username))

class addAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("account_name", "account_type")

class addTransactionForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ("transaction_name", "transaction_amount", "transaction_location", "transaction_date", "account", "category")
        widgets = {
            'transaction_date' : forms.DateInput(attrs={'type':'date'})
        }


class queryForm(forms.Form):
    startDate = forms.DateField(label="Start Date", widget=forms.DateInput(attrs={'type':'date'}), required=True)
    endDate = forms.DateField(label="End Date", widget=forms.DateInput(attrs={'type':'date'}), required=True)
    Min = forms.DecimalField(decimal_places=2, required=True)
    Max = forms.DecimalField(decimal_places=2, required=True)

mango/views.py
from django.shortcuts import render, redirect
from django.db import connection
from mango.models import userAccount, Account, Transactions, Category
from mango.forms import registrationForm, loginForm, accountUpdateForm, addAccountForm, addTransactionForm, queryForm
from django.contrib.auth import login,logout, authenticate
from django.views import View
from django.views.generic import UpdateView, ListView, DeleteView
from django.urls import reverse_lazy

import datetime

# Create your views here.

# Update View


class transactionUpdate(UpdateView):
    template_name = "mango/transaction_update_form.html"
    queryset = Transactions.objects.all()
    success_url = '/'
    form_class = addTransactionForm

    def get_queryset(self):
        user = self.request.user.user_id
        return self.queryset.filter(
            account__user = user
        )

class transactionDelete(DeleteView):
    template_name = "mango/transaction_delete_form.html"
    queryset = Transactions.objects.all()
    success_url = '/'
    
    def get_queryset(self):
        user = self.request.user.user_id
        return self.queryset.filter(
            account__user = user
        )
class transactionsList(ListView):
    template_name = "mango/transaction_list.html"
    model = Transactions
    queryset = Transactions.objects.all().order_by('-transaction_date')
    success_url = '/'
    def get_queryset(self):
        user = self.request.user.user_id
        return self.queryset.filter(
            account__user = user
        )




def index_view(request):
    context = {}

    user = request.user

    if not request.user.is_authenticated:
        return redirect("mango:login")        

    if(request.POST):
        # DO Post Request
        form = queryForm(request.POST)
        if form.is_valid():
            start = form.cleaned_data["startDate"]
            end = form.cleaned_data["endDate"]
            minAmount = form.cleaned_data["Min"]
            maxAmount = form.cleaned_data["Max"]

            # Transaction Query with parameters
            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT transaction_name, account_name, transaction_amount, transaction_location, transaction_date, category_name 
                    FROM mango_transactions 
                    LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                    INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                    WHERE user_id = %s AND 
                    (transaction_date >= %s AND transaction_date <= %s) AND 
                    (transaction_amount >= %s AND transaction_amount <= %s) ORDER BY transaction_date DESC
                """, [user.user_id, start, end, minAmount, maxAmount])
                allTransactionsQuery = cursor.fetchall()

                if not allTransactionsQuery:
                    context["no_transactions"] = True
                    return render(request, 'mango/index.html', context=context)
                allTransactions = []
                for item in allTransactionsQuery:
                    transactionsDict = {
                        'transaction_name' : item[0],
                        'account_name' : item[1],
                        'transaction_amount' : item[2],
                        'transaction_location' : item[3],
                        'transaction_date' : item[4],
                        'category_name' : item[5]
                    }
                    allTransactions.append(transactionsDict)
                context['allTransactions'] = allTransactions



            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT COUNT(transaction_amount) 
                    FROM mango_transactions 
                    LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                    INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                    WHERE user_id = %s AND 
                    (transaction_date >= %s AND transaction_date <= %s) AND 
                    (transaction_amount >= %s AND transaction_amount <= %s)  ORDER BY transaction_date DESC
                """, [user.user_id, start, end, minAmount, maxAmount])
                TransactionsQuery = cursor.fetchone()[0]
                context["number_transaction"] = TransactionsQuery

            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT AVG(transaction_amount) 
                    FROM mango_transactions 
                    LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                    INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                    WHERE user_id = %s AND 
                    (transaction_date >= %s AND transaction_date <= %s) AND 
                    (transaction_amount >= %s AND transaction_amount <= %s)  ORDER BY transaction_date DESC
                """, [user.user_id, start, end, minAmount, maxAmount])
                TransactionsQuery = round(cursor.fetchone()[0], 2)
                context["average_transaction"] = TransactionsQuery

            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT SUM(transaction_amount) 
                    FROM mango_transactions 
                    LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                    INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                    WHERE user_id = %s AND 
                    (transaction_date >= %s AND transaction_date <= %s) AND 
                    (transaction_amount >= %s AND transaction_amount <= %s)  ORDER BY transaction_date DESC
                """, [user.user_id, start, end, minAmount, maxAmount])
                TransactionsQuery = round(cursor.fetchone()[0], 2)
                context["sum_transaction"] = TransactionsQuery


                newForm = queryForm(    initial={'startDate': start, 'endDate': end, "Min" : minAmount, "Max" : maxAmount }) 
                
                context['query_form'] = newForm

        else:
            context['query_form'] = form
    else:
        # Regular transaction
        form = queryForm()
        context['query_form'] = form


        # Transaction Query
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT transaction_name, account_name, transaction_amount, transaction_location, transaction_date, category_name 
                FROM mango_transactions 
                LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                WHERE user_id = %s  ORDER BY transaction_date DESC
            """, [user.user_id])
            allTransactionsQuery = cursor.fetchall()
            if not allTransactionsQuery:
                context["no_transactions"] = True
                return render(request, 'mango/index.html', context=context)
            else:
                context["no_transactions"] = False
            allTransactions = []
            for item in allTransactionsQuery:
                transactionsDict = {
                    'transaction_name' : item[0],
                    'account_name' : item[1],
                    'transaction_amount' : item[2],
                    'transaction_location' : item[3],
                    'transaction_date' : item[4],
                    'category_name' : item[5]
                }
                allTransactions.append(transactionsDict)
            context['allTransactions'] = allTransactions
        


        # Get number of transactins
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(transaction_name)
                FROM mango_transactions 
                LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                WHERE user_id = %s  ORDER BY transaction_date DESC
            """, [user.user_id])
            TransactionsQuery = cursor.fetchone()[0]
            context["number_transaction"] = TransactionsQuery

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT AVG(transaction_amount)
                FROM mango_transactions 
                LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                WHERE user_id = %s  ORDER BY transaction_date DESC
            """, [user.user_id])
            TransactionsQuery = round( cursor.fetchone()[0], 2)
            context["average_transaction"] = TransactionsQuery    

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT SUM(transaction_amount)
                FROM mango_transactions 
                LEFT JOIN mango_category ON mango_transactions.category_ID = mango_category.category_ID
                INNER JOIN mango_account ON mango_transactions.account_id = mango_account.account_ID
                WHERE user_id = %s  ORDER BY transaction_date DESC 
            """, [user.user_id])
            TransactionsQuery = round( cursor.fetchone()[0], 2)
            context["sum_transaction"] = TransactionsQuery       



    return render(request, 'mango/index.html', context=context)

def register_view(request):
    context = {}
    if request.POST:
        form = registrationForm(request.POST)
        if form.is_valid():
            form.save()

templates/mango/account.html
{% extends 'mango/base.html' %}
{% load staticfiles %}


{% block body_block %}


<div class="container">
        <!-- Flex Box -->
    <div class="d-flex flex-column">
        <style type="text/css">
            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }


            .form-signin .form-control {
                position: relative;
                box-sizing: border-box;
                height: auto;
                padding: 10px;
                font-size: 16px;
            }

            .form-signin .form-control:focus {
                z-index: 2;
            }

            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }

            .form-signin input[type="username"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
            .h3{
                text-align: center;
            }
        </style>

        <form action="{% url 'mango:add_account' %}">
            <input type="submit" value="Add Account">
        </form>

        <br>        

        <form action="{% url 'mango:add_transaction' %}">
            <input type="submit" value="Create Transaction">
        </form>

        <br>

        <form action="{% url 'mango:transaction_list' %}">
                <input type="submit" value="Modify Transactions">
        </form>


        <br>
        <form id='plaid-link-form'></form>
        <script
            src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"
            data-client-name="Mango"
            data-form-id="plaid-link-form"
            data-key="e9ff349fb8fd8b6bc5ef02d33d93e4"
            data-product="auth"
            data-env="sandbox">
        </script>
    </div>  
</div>

{% endblock %}

templates/mango/add_account.html
{% extends 'mango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Account
{% endblock %}

{% block body_block %}
<div class="container">
        <!-- Flex Box -->
    <div class="d-flex flex-column">

        <h2>Add Account</h2>
        <form method="POST">
            {% csrf_token %}
            {{ add_account_form.as_p }}
            <button type="submit">Add account</button>
        </form>
    </div>
</div>
{% endblock %}

templates/mango/add_transaction.html
{% extends 'mango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Transaction
{% endblock %}

{% block body_block %}
    <h2>Add Transaction</h2>
    <form method="POST">
        {% csrf_token %}
        {{ add_transaction_form.as_p }}
        <button type="submit">Add Transaction</button>
    </form>
{% endblock %}

templates/mango/base.html
<!doctype html>
{% load staticfiles %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
  <meta charset="utf-8">  
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <title>Mango</title>
    {% include 'snippets/header.html' %}
  </head>
  <body>

    <!-- Body -->
    <style type="text/css">
      .main{
        min-height: 100vh;
        height: 100%;
      }
    </style>
    <div class="main">
      {% block body_block %}

      {% endblock %}
    </div>

    <!-- End Body -->

    {% include 'snippets/footer.html' %}

  </body>
</html>

templates/mango/index.html
{% extends 'mango/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Mango Money</h1>
        {% if user.is_authenticated %}
            <p class="lead">    
                Here is a summary of your accounts           
            </p>
        {% else %}
            <p class="lead">    
                Please sign in to view summary of accounts
            </p>
        {% endif %}
</div>

<div class="container">
    <!-- Flex Box -->
    <div class="d-flex flex-column">


        {% if no_transactions %}
            <p>
                There are no transactions to display, please add them from the account page!
            </p>
        {% else %}
            <form method="POST">
                    {% csrf_token %}
                    {{ query_form }}
                <button type="submit">Make Query</button>
            </form>

            <div>
                <p>The number of transactions is {{ number_transaction }} </p>
                <p>The average amount per transaction is {{ average_transaction }}</p>
                <p>The total is {{ sum_transaction }}</p>

            </div>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Account</th>
                    <th>Amount</th>
                    <th>Location</th>
                    <th>Category</th>
                    <th>date</th>
                </tr>
                {% for item in allTransactions %}
                <tr>
                    <td>{{ item.transaction_name }}</td>
                    <td>{{ item.account_name }}</td>
                    <td>{{ item.transaction_amount }}</td>
                    <td>{{ item.transaction_location }}</td>
                    <td>{{ item.category_name }}</td>
                    <td>{{ item.transaction_date }}</td>

                </tr>
                {% endfor %}
            </table>


<br>
<br>

<!-- ***************************************************************************************** -->
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>  
<style>
        #map{
          height:400px;
          width:100%;
        }
</style>
  <div id="map"></div>
  <script>
    function initMap(){
      // console.log(latCoord);
      // Map options
      var addresses = []
      {% for item in allTransactions %}
        addresses.push( '{{ item.transaction_location }}' );
      {% endfor %}
      // var addresses = ["1119 Spirit Way, Tallahassee, FL 32304", "312 Stadium Drive, Tallahassee, FL 32304", "322 Stadium Dr, Tallahassee, FL","7411 Dover Court Parkland, Fl"];

      var lats = [];
      var lngs = [];

      for(var i = 0; i < addresses.length; i++){
        var location = addresses[i];

        axios.get('https://maps.googleapis.com/maps/api/geocode/json',{
        params:{
          address:location,
          key:'AIzaSyCIazL1Lf3GC4O5gVhJSkbdcyqsTqt9R2I'
        }
        })
        .then(function(response){
          // Log full response
          console.log(response);
          latCoord = response.data.results[0].geometry.location.lat;
          lats.push(latCoord);
          lngCoord = response.data.results[0].geometry.location.lng;
          lngs.push(lngCoord);
          // console.log(latCoord);
          // Formatted Address

        var options = {
          zoom:17,
          center:{lat:latCoord,lng:lngCoord}
        }

        // New map
        var map = new google.maps.Map(document.getElementById('map'), options);

<!--        // Listen for click on map-->
<!--        google.maps.event.addListener(map, 'click', function(event){-->
<!--          // Add marker-->
<!--          addMarker({coords:event.latLng});-->
<!--        });-->

        // Loop through markers
        for(var j = 0;j < lats.length;j++){
          // Add marker
          addMarker({coords:{lat:lats[j],lng: lngs[j]}});
        }

        //addMarker({coords:{lat:30.442762, lng-84.30659})

        // Add Marker Function
        function addMarker(props){
          var marker = new google.maps.Marker({
            position:props.coords,
            map:map,
            //icon:props.iconImage
          });

          // Check for customicon
          if(props.iconImage){
            // Set icon image
            marker.setIcon(props.iconImage);
          }

          // Check content
          if(props.content){
            var infoWindow = new google.maps.InfoWindow({
              content:props.content
            });

            marker.addListener('click', function(){
              infoWindow.open(map, marker);
            });
          }
        }
        })
      }
    }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIazL1Lf3GC4O5gVhJSkbdcyqsTqt9R2I&callback=initMap">
    </script>


<!-- Kevin waz here -->

<!-- ***************************************************************************************** -->


    </div>
</div>
{% endif %}

{% endblock %}

templates/mango/login.html
{% extends 'mango/base.html' %}
{% load staticfiles %}


{% block body_block %}

<style type="text/css">
    .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    }

    .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
    }
    .form-signin .form-control:focus {
    z-index: 2;
    }
    .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    }
    .h3{
        text-align: center;
    }
</style>


<form class="form-signin" method="POST">
    {% csrf_token %}

    <h1 class="h3 mb-3 font-weight-normal">Login</h1>

    <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

    <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>

    
    {% for field in login_form %}
        <p>
        {% for error in field.errors %}
            <p style="color: red;">{{ field.help_text }}</p>
        {% endfor %}
        </p>    
    {% endfor %}
    
    {% if login_form.non_field_errors %}
    <div style="color:red">
        <p>{{ login_form.non_field_errors }}</p>
    </div>
    {% endif %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
</form>
      

{% endblock %}

templates/mango/register.html
{% extends 'mango/base.html' %}


{% block body_block %}


<style type="text/css">
  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
  }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .h3{
    text-align: center;
  }

</style>


<form class="form-signin" method="post">{% csrf_token %}

  <h1 class="h3 mb-3 font-weight-normal">Register an account</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

  <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>
  
  <input type="text" name="first_name" id="inputFirstName" class="form-control" placeholder="First Name" required>

  <input type="text" name="last_name" id="inputLastName" class="form-control" placeholder="Last Name" required>

  <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

  <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>

  {% for field in registration_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if registration_form.non_field_errors %}
    <div style="color: red">
      <p>{{registration_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

</form>


{% endblock body_block %}

templates/mango/transaction_detail.html
{% extends 'mango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Transaction
{% endblock %}

{% block body_block %}
    <h2>Transaction Detail</h2>
    <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" />
    </form>
{% endblock %}

templates/mango/transaction_list.html
{% extends 'mango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Transaction 
{% endblock %}

{% block body_block %}
<div class="container">
        <!-- Flex Box -->
    <div class="d-flex flex-column">
        <table>
                <tr>
                    <th>Name</th>
                    <th>Account</th>
                    <th>Amount</th>
                    <th>Location</th>
                    <th>Category</th>
                    <th>date</th>
                    <th>Update Transaction</th>
                    <th>Delete Transaction</th>
                
                </tr>
        {% for item in object_list %}
            <tr>
                <td> {{ item.transaction_name }}</td>
                <td>{{ item.account  }}</td>
                <td>{{ item.transaction_amount }}</td>
                <td>{{ item.transaction_location }}</td>
                <td>{{ item.category }}</td>
                <td>{{ item.transaction_date }}</td>
                <td> <a href=" {% url 'mango:update_transaction' item.transaction_ID %} ">Update Transaction</a> </td>
                <td> <a href=" {% url 'mango:delete_transaction' item.transaction_ID %}">Delete Transaction</a> </td>

            </tr>
        {% endfor %}

        </table>
    </div>
</div>

{% endblock %}