mango/urls.py
from django.urls import path
from django.conf.urls import url
from mango import views
from .views import transactionUpdate, transactionsList, transactionDelete

app_name = 'mango'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/', views.account_view, name='account'),
    path('account/add_account/', views.add_account_view, name='add_account'),
    path('account/add_transaction/', views.add_transaction_view, name="add_transaction"),
    path('account/transactions_list', transactionsList.as_view(), name="transaction_list"),
    path('account/transactions_list/update_transaction/<int:pk>', transactionUpdate.as_view(), name="update_transaction"),
    path('account/transactions_list/delete_transaction/<int:pk>', transactionDelete.as_view(), name="delete_transaction"),

]

mango_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from mango import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name="index"),
    path('mango/', include("mango.urls")),

]

templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 100px;
    }
</style>

<!-- footer -->
<hr>
<div class="d-flex flex-row align-items-center footer">
    <p class="m-auto">Mango Finance App</p>
</div>
<!-- footer end -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/snippets/header.html
<!-- Bootstrap CSS -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<style type="text/css">
    @media (min-width: 768px) {
    html {
        font-size: 16px;
    }
    }
    .container {    <a class="btn btn-outline-primary" href="{% url 'mango:register' %}">Sign up</a>

    max-width: 960px;
    }
    .pricing-header {
    max-width: 700px;
    }
    .card-deck .card {
    min-width: 220px;
    }
</style>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        {% if request.user.is_authenticated %}
            <p class="p-2 text-dark">Hello, {{ request.user.username }}</p>
        {% endif %}</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'mango:index' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'mango:account' %}">Account</a>
            <a class="p-2 text-dark" href="{% url 'mango:logout' %}">Logout</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'mango:index' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'mango:login' %}">Login</a>
            <a class="btn btn-outline-primary" href="{% url 'mango:register' %}">Sign up</a>
        {% endif %}
    </nav>
</div>
      


<title>
    Mango {% block title_block %} {% endblock %}
</title>